name: Build APK

on:
  workflow_dispatch:

# Hier schalten wir die Node 24 Warnung ab:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Android Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev lld cmake auto-apt-proxy unzip wget python3-pip python3-setuptools
          pip install --upgrade pip
          pip install --upgrade setuptools wheel virtualenv
          pip install "cython<3.0" buildozer

      - name: Force Install Android SDK and Create Legacy Symlink
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
          mv ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk --licenses || true
          
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk "build-tools;33.0.0" "platforms;android-33" "platform-tools"

      - name: Build APK with Buildozer
        run: |
          export ANDROIDSDK=/home/runner/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROIDSDK/platform-tools:$ANDROIDSDK/tools/bin
          buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Kivy-App
          path: bin/*.apk
